sudo: required

matrix:
  include:
    - language: python
      python: 2.7.12
      os: linux
      env: SKIP_INTERPRETER=true
      before_install:
        - pip install --upgrade setuptools
        - git clone https://github.com/TravisToolbox/pycodestyle-travis.git
      install:
        - "./pycodestyle-travis/install.sh"
      script:
        - "./pycodestyle-travis/scan.sh"

    - language: node_js
      before_install:
        - sudo npm install -g @angular/cli # Install ng programs 
      node_js:
        - "8"
      script:
        - ng lint
        - ng test
