branch-defaults:
  default:
    environment: outdoor-ed
    group_suffix: null
environment-defaults:
  apex-matching:
    branch: null
    repository: null
  outdoor-ed:
    branch: null
    repository: null
global:
  application_name: apex-matching
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 2.7
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
